.github/workflows/main.yml
.gitignore
Package.resolved
Package.swift
Sources/CLI/Run/RunCommand.swift

Willow (even its latest version) currently breaks the build with this error:
```
error: target at 'WAKit/.build/checkouts/Willow' contains mixed language source files; 
feature not supported
```
Apple's [`swift-log`](https://github.com/apple/swift-log.git) seems to be a well-supported alternative, it was quite easy to replace Willow with it.
GitHub Actions now test on both macOS and Linux.

Replace Willow w/ swift-log, Bitrise w/ GH Actions

---

Sources/WAKit/Execution/Instructions/Memory.swift
Sources/WAKit/Execution/Types/Instances.swift
Sources/WAKit/Parser/Wasm/WasmParser.swift
Tests/WAKitTests/Execution/Instructions/ControlInstructionTests.swift

This change fixes `load` instructions not respecting bit width parts. For example, `i32.load8_u` was loading all i32 bytes instead of a single byte.
Also, the page size was specified as 6K, while it's 64K according to the spec.
This increases the amount of spec tests passing from 25% in `master` to 33% in this branch.

Fix memory load with limited bit width

---

.github/workflows/main.yml
Sources/CLI/SpecTest/SpecTestCommand.swift
Sources/CLI/SpecTest/TestCase.swift
Sources/WAKit/Execution/Instructions/Memory.swift
Sources/WAKit/Execution/Types/Instances.swift
Sources/WAKit/Parser/Wasm/WasmParser.swift
Tests/WAKitTests/Execution/Instructions/ControlInstructionTests.swift

Now the `spectest` command prints a summary after the test run has completed in this form:
```
6309/19331 32% passing
```
I've also fixed `nan` values not being parsed in test cases.

Print passing/total counts of test cases

---

Package.resolved
Package.swift
Sources/CLI/Run/Run.swift
Sources/Spectest/Spectest.swift
Sources/Spectest/TestCase.swift

swift-log is only used in the top-level executable targets and it means we don't need logging abstraction layer for now. Reducing the number of dependencies makes it easier to integrate in apple/swift build system.

Remove swift-log dependency

---

Sources/WasmKit/Execution/Runtime/Store.swift
Tests/WasmKitTests/Execution/HostModuleTests.swift

When using WasmKit, in certain cases we need `HostModule` to provide a host memory instance, as opposed to an already supported case, where a parsed module has its own guest memory.

Expose a way to allocate a memory from host

---

Sources/WasmKit/Execution/Runtime/Store.swift
Sources/WasmKit/Execution/Types/Instances.swift
Sources/WasmKit/Parser/Wasm/WasmParser.swift
Sources/WasmKit/Types/Module.swift
Tests/WasmKitTests/Execution/Instructions/ControlInstructionTests.swift

This resolves a naming collision between the existing `Function` type declared in `Types/Module.swift` and `Runtime/Function.swift` that in a subsequent change fails the build with these errors:
```
WasmKit/Types/Module.swift:21:21: error: 'Function' is ambiguous for type lookup in this context
functions: [Function] = [],
^~~~~~~~
WasmKit/Execution/Runtime/Function.swift:1:15: note: found this candidate
public struct Function: Equatable {
^
WasmKit/Types/Module.swift:70:15: note: found this candidate
public struct Function {
```

Mark `Function` as `internal` and rename it as `GuestFunction`

---

Sources/Spectest/TestCase.swift
Sources/WasmKit/Component/CanonicalCall.swift
Sources/WasmKit/Component/CanonicalOptions.swift
Sources/WasmKit/Execution/Instructions/Control.swift
Sources/WasmKit/Execution/Instructions/Table.swift
Sources/WasmKit/Execution/Runtime/ExecutionState.swift
Sources/WasmKit/Execution/Runtime/Function.swift
Sources/WasmKit/Execution/Runtime/Runtime.swift
Sources/WasmKit/Execution/Runtime/Store.swift
Sources/WasmKit/Execution/Types/Instances.swift
Tests/WasmKitTests/Execution/Instructions/ControlInstructionTests.swift
Tests/WasmKitTests/Execution/Instructions/VariableInstructionTests.swift

`Runtime` no longer manages the execution state of a guest program. Separating the execution state makes it easier to have a fresh stack for each invocation of an exported function. Also it's now safe to provide a way to access `Runtime` during `HostFunction` execution since no mutable execution state is exposed.
Additionally, tests were added to verify the new API surface.

Extract `ExecutionState` from the `Runtime` type

---

Sources/WasmKit/Execution/Runtime/ExecutionState.swift
Sources/WasmKit/Execution/Runtime/Function.swift
Sources/WasmKit/Execution/Runtime/Store.swift
Tests/WasmKitTests/Execution/HostModuleTests.swift

Since `Runtime` manages the single execution state, it wrongly executes upper frame instructions if the call stack is `guest -> host -> guest`. This change creates a fresh execution state for each exported guest function invocation and adds test coverage to verify that it fixes the issue.

Support reentrant function call between host/guest

---

CMakeLists.txt
Sources/CLI/CMakeLists.txt
Sources/CMakeLists.txt
cmake/modules/AddSwiftHostLibrary.cmake

This enables building and installing wasmkit-cli with CMake. At some point we might want to update the `wasmkit.py` product in the Swift repo to use this instead of `swift build`, since we're already building WasmKit via CMake for swift-wasm-plugin-server.

Support building CLI via CMake

---

Sources/WASI/RandomBufferGenerator.swift
Sources/WASI/WASI.swift
Tests/WASITests/RandomBufferGeneratorTests.swift

This protocol allows to inject a custom random number generator for `wasi_snapshot_preview1::random_get` function. The default implementation continues to use `swift_stdlib_random` function but users can provide their own implementation. Additionally, types conforming to `RandomNumberGenerator` can automatically conform to the new protocol.
This is useful when we want fully deterministic behavior like build tools or tests.
Resolves a part of https://github.com/swiftwasm/WasmKit/issues/84

Add RandomBufferGenerator protocol for WASI random_get

---

Sources/WASI/Clock.swift
Sources/WASI/Platform/PlatformTypes.swift
Sources/WASI/WASI.swift

This commit adds `WallClock` and `MononicClock` protocols to the WASI module. These protocols are used to abstract clocks in WASI implementations. This is useful when we want fully deterministic behavior like for build systems or tests.
Resolve a part of https://github.com/swiftwasm/WasmKit/issues/84

Add `WallClock` and `MonotonicClock` protocols

---

.gitmodules
CI/check-spectest.sh
CI/check-wasi-testsuite.sh
Makefile
README.md
Vendor/.gitignore
Vendor/checkout-dependency
Vendor/dependencies.json

git-submodule was good for us to manage the dependencies without hassle, but it adds quite a few overheads to fetch this package as a SwiftPM package dependency. This commit removes the git-submodules and adds a Makefile to fetch the test suite repositories manually.

Checkout test suite repositories without git-submodules

---

.github/workflows/main.yml
Package.swift
Sources/CLI/Run/Run.swift
Sources/Spectest/Spectest.swift
Sources/Spectest/TestCase.swift
Sources/SystemExtras/Clock.swift
Sources/SystemExtras/Constants.swift
Sources/SystemExtras/FileAtOperations.swift
Sources/SystemExtras/Syscalls.swift
Sources/SystemExtras/Vendor/Utils.swift
Sources/WasmKit/Execution/Runtime/Profiler.swift
Sources/WasmKit/ModuleParser.swift
Tests/WITExtractorTests/TestSupport.swift

This is an initial attempt to port WasmKit to work on Windows. This change only ports WasmKit core engine, not including WASI implementation for now.

Initial Windows Support

---

.github/workflows/main.yml

because actions/checkout requires recent version of glibc, which is not always available in the Swift container like amazonlinux2.

Stop using Swift container at job-level

---

cmake/modules/AddSwiftHostLibrary.cmake

We were previously appending to `SWIFT_EXPORTS` which has a special meaning for in-tree swiftc builds. This was causing us to export WasmKit to all consumers of the Swift Compiler via CMake. Specifically, this resulted in failing builds of Swift's LLDB fork: see https://github.com/swiftlang/swift/pull/73031#issuecomment-2227365165.
We can fix this by using a different property name.

Fix CMake export

---

Examples/Sources/Factorial/Factorial.swift
Examples/Sources/PrintAdd/PrintAdd.swift
Examples/Sources/WASI-Hello/Hello.swift

I was exploring WasmKit this morning with Xcode 16 beta 5 (Swift 6 compiler), and none of the examples would compile smoothly there. I thought this PR would resolve this for others trying to do the same.

global variable initialization isn't allow with throw in swift6 compiler - adds boilerplate main() around the examples showing use of WasmKit

---

FuzzTesting/README.md
FuzzTesting/differential.py
Sources/SystemExtras/FileAtOperations.swift
Sources/SystemExtras/Vendor/Exports.swift
Sources/WASI/Platform/Entry.swift
Sources/WASI/Platform/SandboxPrimitives/Open.swift
Sources/WITOverlayGenerator/CanonicalABI/StaticCanonicalDeallocation.swift
Sources/WITOverlayGenerator/CanonicalABI/StaticCanonicalLowering.swift
Sources/WITOverlayGenerator/HostGenerators/HostExportFunction.swift
Tests/WITTests/Semantics/ValidationTests.swift

No public **source** code change, comments mostly.

Fix some typos

---

Sources/CLI/Commands/Run.swift
Sources/WasmKit/Execution/Instructions/Control.swift
Sources/WasmKit/Execution/Instructions/Expression.swift
Sources/WasmKit/Execution/Instructions/Instruction.swift
Sources/WasmKit/Execution/Instructions/InstructionSupport.swift
Sources/WasmKit/Execution/Runtime/Function.swift
Sources/WasmKit/Execution/Runtime/InstDispatch.swift
Sources/WasmKit/Execution/Runtime/NameRegistry.swift
Sources/WasmKit/Execution/Runtime/Profiler.swift
Sources/WasmKit/Execution/Runtime/Runtime.swift
Sources/WasmKit/Execution/Runtime/StoreAllocator.swift
Sources/WasmKit/Execution/Types/Instances.swift
Sources/WasmKit/Translator.swift
Tests/WasmKitTests/EngineTests.swift
Tests/WasmKitTests/TranslatorTests.swift
Utilities/Sources/GenerateInternalInstruction.swift

The guest time profiler had been disabled by default build configuration
because the interceptor mechanism added non-negligible overhead to the
execution even when the profiler is not used due to the conditional call
to the interceptor methods on every function call.
The translation layer enables the conditional interceptor call to appear
only when the profiler is enabled. The translated ISeq will contain
`onEnter` and `onExit` instructions at the beginning and the end of each
function, respectively, if the profiler is enabled.
```
;; When profiler is enabled
i32.const 0
i32.const 1
i32.add
end
;; When profiler is disabled
on_enter
i32.const 0
i32.const 1
i32.add
on_exit
end
```

Re-introduce guest time profiler without overhead when not used 

---

Sources/WAT/Encoder.swift
Sources/WAT/Lexer.swift
Sources/WAT/NameMapping.swift
Sources/WAT/Parser.swift
Sources/WAT/Parser/ExpressionParser.swift
Sources/WAT/Parser/WastParser.swift
Sources/WAT/Parser/WatParser.swift
Sources/WAT/WAT.swift
Sources/WasmKit/Engine.swift
Sources/WasmKit/Execution/Execution.swift
Sources/WasmKit/Execution/Function.swift
Sources/WasmKit/Execution/Instances.swift
Sources/WasmKit/Execution/Instructions/Control.swift
Sources/WasmKit/Module.swift
Tests/WATTests/EncoderTests.swift
Tests/WATTests/ParserTests.swift
Tests/WATTests/Spectest.swift
Tests/WATTests/TestSupport.swift
Tests/WasmKitTests/FuzzTranslatorRegressionTests.swift
Tests/WasmKitTests/Spectest/TestCase.swift

And it revealed several issues in WAT parser

Tests: Fix `assert_malformed` assertion

---

CMakeLists.txt

The new interpreter heavily benefits from WMO and it's even slower than the old one without it. This change enables WMO for Release builds for CMake builds as it's not enabled by default.
Use `CMAKE_Swift_COMPILATION_MODE` if CMake 3.29 or newer is used, and fall back to `add_compile_options` if older.
https://cmake.org/cmake/help/latest/prop_tgt/Swift_COMPILATION_MODE.html

CMake: Enable WMO for Release builds

---

Sources/WasmParser/LEB.swift
Sources/WasmParser/ParsingLimits.swift
Sources/WasmParser/Stream/Stream.swift
Sources/WasmParser/WasmParser.swift
Sources/WasmParser/WasmTypes.swift

With this change, we can achieve 17% speedup on stringify macro
benchmark. The performance number is same as the case with CMO but with
smaller binary size.
|            | baseline | CMO   | this change |
|------------|----------|-------|-------------|
| speed (ms) | 198.1    | 172.8 | 169.9       |
| size  (kb) [^1] | 1739     | 1923  | 1797        |
[^1]: swift-6.0.1-RELEASE, macOS 14.4.1 arm64

WasmParser: Specialize more hot paths

---

Sources/WAT/Encoder.swift
Sources/WasmKit/Execution/UntypedValue.swift
Sources/WasmParser/WasmParser.swift
Sources/WasmTypes/WasmTypes.swift

Nothing is implemented yet but just not to prevent parsing a name section of a module with SIMD types.

Minimal SIMD types support

---

Sources/WasmKit/Execution/Execution.swift

Fix a trivial doc comment that was misnamed.

Docs: runtime -> store doc update

---

Sources/CLI/Commands/Run.swift

Align with the wasmtime CLI behavior

CLI: Use `.captureForPassthrough` for `Run` command arguments

---

.github/workflows/main.yml

To see if the latest release fixed incompatibility with recent GitHub Actions Windows runners.
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\include\xmmintrin.h:79:10: error: cyclic dependency in module 'ucrt': ucrt -> _visualc_intrinsics -> ucrt
#include <malloc.h>
```
https://github.com/compnerd/swift-build/issues/909

CI: Update Windows toolchain to Swift 6.0.3

---

Sources/SystemExtras/FileOperations.swift
Sources/SystemExtras/Syscalls.swift
Sources/WASI/FileSystem.swift
Sources/WASI/Platform/File.swift
Sources/WASI/WASI.swift

WASI: Implement `fd_sync`

---

Sources/SystemExtras/FileOperations.swift
Sources/SystemExtras/Syscalls.swift
Sources/WASI/FileSystem.swift
Sources/WASI/Platform/File.swift
Sources/WASI/WASI.swift

I added implementation of `fd_datasync` following `fd_sync` #180.
- On Darwin
- behaves exactly like `fd_sync` (`fcntl(fd, F_FULLFSYNC)`)
- On Windows
- behaves exactly like `fd_sync` (`FlushFileBuffers`)
- On UNIX-like systems except for Darwin
- uses `fdatasync(fd)`
- On other systems that don't have `fdatasync` (e.g. Haiku)
- uses `fsync(fd)` instead
References:
- https://github.com/WebAssembly/WASI/blob/9df56e7b858ca9a1a47d2cf8bbcf5391e3f5d773/legacy/preview1/docs.md#-fd_datasyncfd-fd---result-errno
- https://wasix.org/docs/api-reference/wasi/fd_datasync
- Darwin
- https://transactional.blog/blog/2022-darwins-deceptive-durability
- https://github.com/rust-lang/rust/blob/f1bc669636023c8643602431791c7f26e5a6edef/library/std/src/sys/fs/unix.rs#L1224
- Windows
- …

WASI: Implement `fd_datasync`

---

.github/workflows/main.yml
Tests/WITExtractorPluginTests/PluginSmokeTests.swift

> This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101

CI: Update GitHub Actions runs-on to Ubuntu 22.04

---

.github/workflows/main.yml
Package.swift
Sources/SystemExtras/Clock.swift
Sources/SystemExtras/Constants.swift
Sources/SystemExtras/FileAtOperations.swift
Sources/SystemExtras/FileOperations.swift
Sources/SystemExtras/Syscalls.swift
Sources/SystemExtras/Vendor/Exports.swift
Sources/WASI/Clock.swift
Sources/WASI/Platform/Entry.swift
Sources/WASI/Platform/SandboxPrimitives/Open.swift
Sources/WASI/WASI.swift
Sources/WasmKit/Execution/Profiler.swift
Tests/WASITests/IntegrationTests.swift
Tests/WASITests/TestSupport.swift
Tests/WATTests/TestSupport.swift
Tests/WITExtractorPluginTests/TestSupport.swift
Tests/WITExtractorTests/TestSupport.swift
Tests/WITOverlayGeneratorTests/HostGeneratorTests.swift
Tests/WasmKitTests/FuzzTranslatorRegressionTests.swift
Tests/WasmKitTests/SpectestTests.swift

This PR adds support for building and testing on Android. It mostly just adds `#if os(Android)` checks and some Android-specific fixes for things like `errno` and `O_SYNC`, which are implemented differently in Bionic than Linux/Musl.
Android does require swift-system 1.5+, so I made the dependency `upToNextMajor` from "1.3.0" rather than `upToNextMinor`. If that presents an issue, we could probably finagle some mechanism for having different swift-system version requirements based on the platform.
Test cases are run with [swift-android-action](https://github.com/marketplace/actions/swift-android-action), which installs the Android SDK and runs the test cases on an Android emulator. Some of the tests that expect hard-coded file paths had to be disabled because the Android emulator doesn't …

Android support

---

Sources/CLI/Commands/Parse.swift
Sources/CLI/Commands/Run.swift

Convert parseWasm() to be a global function instead of an an instance method of the Run command. This wraps WasmKit.parseWasm() and supports both ".wat" and ".wasm" files.

Support exploring ".wat" files

---

.github/workflows/main.yml
Package.swift
Tests/WITOverlayGeneratorTests/Runtime/RuntimeTestHarness.swift

We should ensure that WasmKit is tested with newer versions of Swift.
With this change we're also using official Swift SDKs from swift.org.
Support for versions older than 6.0 is dropped to keep the support matrix size reasonable.

Expand/update testing matrix in `main.yml`
